import { useState } from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [longUrl, setLongUrl] = useState<any>("")
  const [error, setErr] = useState<any | null>(null)
  const handler = async (e: any) => {
  
    e.preventDefault()
    console.log(longUrl)
    try {
      if(longUrl === ""){
        setErr("Please Put Your Long Url")
      }else{
        let res = await axios.post("/api/makeshort", {
          longUrl
        })
        console.log(res)
        setLongUrl(res.data.data.shortUrl)
        setErr("")
        console.log(res.data.data.shortUrl)
      }
    
    } catch (error:any) {
      console.log(error)
      setErr(error.response.data.message)
    }
  }
  return (
    <>
      <Head>
        <title>Short url</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="main-container">
        <div className='first-container same'>
          <h2>Shorten a long URL</h2>
          <input
            className='input'
            type="text"
            placeholder='Enter Your Long Url'
            value={longUrl}
            onChange={(e) => setLongUrl(e.target.value)} /><br />
          {error ? <h1 className='error'>{error}</h1> : ""}
          <button onClick={handler}>Make Short</button>
        </div>
        <div className='second-container same'>
            <h3>ShortUrl is a URL shortening web service, which provides short aliases for redirection of long URLs</h3>
            <h2>Benefits:-</h2>
            <ul>
              <li>More streamlined in appearance</li>
              <li>Easier to replicate</li>
              <li>Tracking capabilities</li>
              <li>More legitimacy</li>
            </ul>
        </div>
      </section>


    </>
  )
}
